spring:
  profiles:
    active: dev
  application:
    name: mall-project
  jackson:
    # 指定时区
    time-zone: Asia/Shanghai
mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 9090
