spring:
  profiles:
    active: dev
  application:
    name: mall-project
  jackson:
    # 指定时区
    time-zone: Asia/Shanghai
    # 响应实体中的字段为null时不返回
    default-property-inclusion: non_empty
    # 响应时间类型全部转换为该格式
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 9090
